CREATE TABLE [dbo].[GameRating] (
    [title]                    VARCHAR (200) NOT NULL,
    [console]                  INT           NULL,
    [alcohol_reference]        INT           NULL,
    [animated_blood]           INT           NULL,
    [blood]                    INT           NULL,
    [blood_and_gore]           INT           NULL,
    [cartoon_violence]         INT           NULL,
    [crude_humor]              INT           NULL,
    [drug_reference]           INT           NULL,
    [fantasy_violence]         INT           NULL,
    [intense_violence]         INT           NULL,
    [language]                 INT           NULL,
    [lyrics]                   INT           NULL,
    [mature_humor]             INT           NULL,
    [mild_blood]               INT           NULL,
    [mild_cartoon_violence]    INT           NULL,
    [mild_fantasy_violence]    INT           NULL,
    [mild_language]            INT           NULL,
    [mild_lyrics]              INT           NULL,
    [mild_suggestive_themes]   INT           NULL,
    [mild_violence]            INT           NULL,
    [no_descriptors]           INT           NULL,
    [nudity]                   INT           NULL,
    [partial_nudity]           INT           NULL,
    [sexual_content]           INT           NULL,
    [sexual_themes]            INT           NULL,
    [simulated_gambling]       INT           NULL,
    [strong_janguage]          INT           NULL,
    [strong_sexual_content]    INT           NULL,
    [suggestive_themes]        INT           NULL,
    [use_of_alcohol]           INT           NULL,
    [use_of_drugs_and_alcohol] INT           NULL,
    [violence]                 INT           NULL,
    [esrb_rating]              VARCHAR (5)   NULL,
    PRIMARY KEY CLUSTERED ([title] ASC),
    CHECK ([alcohol_reference]>=(0) AND [alcohol_reference]<=(1)),
    CHECK ([animated_blood]>=(0) AND [animated_blood]<=(1)),
    CHECK ([blood]>=(0) AND [blood]<=(1)),
    CHECK ([blood_and_gore]>=(0) AND [blood_and_gore]<=(1)),
    CHECK ([cartoon_violence]>=(0) AND [cartoon_violence]<=(1)),
    CHECK ([console]>=(0) AND [console]<=(1)),
    CHECK ([crude_humor]>=(0) AND [crude_humor]<=(1)),
    CHECK ([drug_reference]>=(0) AND [drug_reference]<=(1)),
    CHECK ([fantasy_violence]>=(0) AND [fantasy_violence]<=(1)),
    CHECK ([intense_violence]>=(0) AND [intense_violence]<=(1)),
    CHECK ([language]>=(0) AND [language]<=(1)),
    CHECK ([lyrics]>=(0) AND [lyrics]<=(1)),
    CHECK ([mature_humor]>=(0) AND [mature_humor]<=(1)),
    CHECK ([mild_blood]>=(0) AND [mild_blood]<=(1)),
    CHECK ([mild_cartoon_violence]>=(0) AND [mild_cartoon_violence]<=(1)),
    CHECK ([mild_fantasy_violence]>=(0) AND [mild_fantasy_violence]<=(1)),
    CHECK ([mild_language]>=(0) AND [mild_language]<=(1)),
    CHECK ([mild_lyrics]>=(0) AND [mild_lyrics]<=(1)),
    CHECK ([mild_suggestive_themes]>=(0) AND [mild_suggestive_themes]<=(1)),
    CHECK ([mild_violence]>=(0) AND [mild_violence]<=(1)),
    CHECK ([no_descriptors]>=(0) AND [no_descriptors]<=(1)),
    CHECK ([nudity]>=(0) AND [nudity]<=(1)),
    CHECK ([partial_nudity]>=(0) AND [partial_nudity]<=(1)),
    CHECK ([sexual_content]>=(0) AND [sexual_content]<=(1)),
    CHECK ([sexual_themes]>=(0) AND [sexual_themes]<=(1)),
    CHECK ([simulated_gambling]>=(0) AND [simulated_gambling]<=(1)),
    CHECK ([strong_janguage]>=(0) AND [strong_janguage]<=(1)),
    CHECK ([strong_sexual_content]>=(0) AND [strong_sexual_content]<=(1)),
    CHECK ([suggestive_themes]>=(0) AND [suggestive_themes]<=(1)),
    CHECK ([use_of_alcohol]>=(0) AND [use_of_alcohol]<=(1)),
    CHECK ([use_of_drugs_and_alcohol]>=(0) AND [use_of_drugs_and_alcohol]<=(1)),
    CHECK ([violence]>=(0) AND [violence]<=(1)),
    FOREIGN KEY ([esrb_rating]) REFERENCES [dbo].[Rating] ([rate])
);

