/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "lamp.h"
#include <stdio.h>
#include <pthread.h>
#include <unistd.h>
#include <stdlib.h>
#include <time.h>


void 
bakery_prog_1(char *host)
{
	CLIENT *clnt;
	struct BAKERY  *result_1;
	struct BAKERY  bakery_proc_1_arg;
	clnt = clnt_create (host, BAKERY_PROG, BAKERY_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	int r = rand() % 2 + 1;
	sleep(r);
	bakery_proc_1_arg.arg = getpid();
	bakery_proc_1_arg.op = GET_NUMBER; 
	result_1 = bakery_proc_1(&bakery_proc_1_arg, clnt);
	if (result_1 == (struct BAKERY *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Client %d get number %d sleep %d \n", result_1->arg2, result_1->arg, r);
	r = rand() % 2 + 2;
	sleep(r);
	bakery_proc_1_arg.op = ENTER_CR; 
	bakery_proc_1_arg.arg = result_1->op;
	bakery_proc_1_arg.arg2 = getpid();
	result_1 = bakery_proc_1(&bakery_proc_1_arg, clnt);
	if (result_1 == (struct BAKERY *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Client %d write %c sleep %d \n", result_1->arg2, result_1->result, r);
	clnt_destroy (clnt);
}


int
main (int argc, char *argv[])
{
	setbuf(stdout, NULL);
	srand(time(NULL));
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	bakery_prog_1(host);
exit (0);
}
