version: '3.1'

services:
  main_db:
    container_name: main
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password_1
    ports:
      - 3000:1433
    networks:
      - net
  replica1_db:
    container_name: replica
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password_1
    ports:
      - 3001:1433
    networks:
      - net
  adminer:
    container_name: admin
    image: adminer:latest
    ports:
      - 9000:8080
    networks:
      - net
      
networks:
  net:
    driver: bridge